AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  DynamodbAccessLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: DynamodbAccessLayer
      Description: A layer for accessing DynamoDB
      ContentUri: s3://dynamodb-access-layer-bucket/6e0462ed6cfd8b098b3a258a66be286f
      CompatibleRuntimes:
      - python3.9
      LicenseInfo: MIT
    Metadata:
      SamResourceId: DynamodbAccessLayer
