AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  DynamodbAccessLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: DynamodbAccessLayer
      Description: A layer for accessing DynamoDB
      ContentUri: ./python
      CompatibleRuntimes:
        - python3.9
      LicenseInfo: MIT
